/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import soundgeneratorgui.imageUtils;

/**
 *
 * @author ibrahim
 */
public class noteSheetPanel extends javax.swing.JPanel {
    noteEditor noteEditorPanel;

    /**
     * Creates new form noteSheetPanel
     */
    public noteSheetPanel() {
        initComponents();
        this.noteEditorPanel=new noteEditor();
        this.noteSheetEditPanel.add(this.noteEditorPanel,BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        leftPanelHideLabel = new javax.swing.JLabel();
        saveFileButton = new javax.swing.JButton();
        composeFileButton = new javax.swing.JButton();
        noteSheetEditPanel = new javax.swing.JPanel();
        leftPanelShowLabel = new javax.swing.JLabel();
        addStaveButtonLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(640, 360));
        setPreferredSize(new java.awt.Dimension(960, 540));
        setLayout(new java.awt.BorderLayout());

        leftPanel.setBackground(new java.awt.Color(200, 255, 255));
        leftPanel.setPreferredSize(new java.awt.Dimension(220, 360));

        leftPanelHideLabel.setMaximumSize(new java.awt.Dimension(80, 80));
        leftPanelHideLabel.setMinimumSize(new java.awt.Dimension(25, 25));
        leftPanelHideLabel.setOpaque(true);
        leftPanelHideLabel.setPreferredSize(new java.awt.Dimension(35, 35));
        leftPanelHideLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftPanelHideLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftPanelHideLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftPanelHideLabelMouseEntered(evt);
            }
        });

        saveFileButton.setBackground(new java.awt.Color(254, 254, 254));
        saveFileButton.setText("save");
        saveFileButton.setFocusable(false);
        saveFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveFileButtonMouseClicked(evt);
            }
        });

        composeFileButton.setBackground(new java.awt.Color(254, 254, 254));
        composeFileButton.setText("Compose");
        composeFileButton.setFocusable(false);
        composeFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                composeFileButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPanelHideLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(composeFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveFileButton)))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPanelHideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveFileButton)
                    .addComponent(composeFileButton))
                .addContainerGap(440, Short.MAX_VALUE))
        );

        ImageIcon menuIcon=new javax.swing.ImageIcon(getClass().getResource("/Images/menu-icon.png"));
        menuIcon=imageUtils.resize(menuIcon, leftPanelHideLabel.getPreferredSize());
        leftPanelHideLabel.setIcon(menuIcon);
        leftPanelHideLabel.setBackground(this.leftPanel.getBackground());

        add(leftPanel, java.awt.BorderLayout.LINE_START);

        noteSheetEditPanel.setBackground(new java.awt.Color(255, 255, 255));
        noteSheetEditPanel.setPreferredSize(new java.awt.Dimension(420, 360));
        noteSheetEditPanel.setLayout(new java.awt.BorderLayout());

        leftPanelShowLabel.setMaximumSize(new java.awt.Dimension(80, 360));
        leftPanelShowLabel.setMinimumSize(new java.awt.Dimension(25, 360));
        leftPanelShowLabel.setOpaque(true);
        leftPanelShowLabel.setPreferredSize(new java.awt.Dimension(35, 360));
        leftPanelShowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftPanelShowLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                leftPanelShowLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                leftPanelShowLabelMouseEntered(evt);
            }
        });
        noteSheetEditPanel.add(leftPanelShowLabel, java.awt.BorderLayout.LINE_START);
        leftPanelShowLabel.setIcon(menuIcon);
        leftPanelShowLabel.setBackground(this.noteSheetEditPanel.getBackground());
        leftPanelShowLabel.setVisible(false);

        addStaveButtonLabel.setFont(new java.awt.Font("Ubuntu", 2, 16)); // NOI18N
        addStaveButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addStaveButtonLabel.setText("Click to add new stave");
        addStaveButtonLabel.setFocusable(false);
        addStaveButtonLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addStaveButtonLabel.setOpaque(true);
        addStaveButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStaveButtonLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addStaveButtonLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStaveButtonLabelMouseEntered(evt);
            }
        });
        noteSheetEditPanel.add(addStaveButtonLabel, java.awt.BorderLayout.PAGE_END);

        add(noteSheetEditPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void leftPanelHideLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelHideLabelMouseEntered
        // TODO add your handling code here:
        this.leftPanelHideLabel.setBackground( this.leftPanel.getBackground().darker());
    }//GEN-LAST:event_leftPanelHideLabelMouseEntered

    private void leftPanelHideLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelHideLabelMouseExited
        // TODO add your handling code here:
        this.leftPanelHideLabel.setBackground( this.leftPanel.getBackground());
    }//GEN-LAST:event_leftPanelHideLabelMouseExited

    private void leftPanelHideLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelHideLabelMouseClicked
        // TODO add your handling code here:
        Thread t=new Thread(){
        @Override
        public void run(){
            
            try{
                Dimension d=leftPanel.getPreferredSize();
                for (int i =(int)d.getWidth(); i >= 0; i--) {
                    
                    Thread.sleep(1);
                    leftPanel.setPreferredSize(new Dimension(i,d.height) );
                    repaint();
                    revalidate();
                }
                leftPanelShowLabel.setVisible(true);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    };t.start();
    }//GEN-LAST:event_leftPanelHideLabelMouseClicked

    private void leftPanelShowLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelShowLabelMouseClicked
        // TODO add your handling code here:
        Thread t=new Thread(){
        @Override
        public void run(){
            
            try{
                leftPanelShowLabel.setVisible(false);
                
                Dimension d=leftPanel.getPreferredSize();
                for (int i =0; i <= 240; i++) {
                    
                    Thread.sleep(1);
                    leftPanel.setPreferredSize(new Dimension(i,d.height) );
                    repaint();
                    revalidate();
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    };t.start();
        
    }//GEN-LAST:event_leftPanelShowLabelMouseClicked

    private void leftPanelShowLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelShowLabelMouseEntered
        // TODO add your handling code here:
        this.leftPanelShowLabel.setBackground( this.noteSheetEditPanel.getBackground().darker());
    }//GEN-LAST:event_leftPanelShowLabelMouseEntered

    private void leftPanelShowLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftPanelShowLabelMouseExited
        // TODO add your handling code here:
        this.leftPanelShowLabel.setBackground( this.noteSheetEditPanel.getBackground());
    }//GEN-LAST:event_leftPanelShowLabelMouseExited

    private void saveFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveFileButtonMouseClicked
        // TODO add your handling code here:
        this.noteEditorPanel.writeToFile();
        
    }//GEN-LAST:event_saveFileButtonMouseClicked

    private void composeFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_composeFileButtonMouseClicked
        // TODO add your handling code here:
        this.noteEditorPanel.ComposeFromFile();
    }//GEN-LAST:event_composeFileButtonMouseClicked

    private void addStaveButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStaveButtonLabelMouseClicked
        // TODO add your handling code here:
        this.noteEditorPanel.addStave();
    }//GEN-LAST:event_addStaveButtonLabelMouseClicked

    private void addStaveButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStaveButtonLabelMouseEntered
        // TODO add your handling code here:
        this.addStaveButtonLabel.setBackground(this.addStaveButtonLabel.getBackground().darker());
    }//GEN-LAST:event_addStaveButtonLabelMouseEntered

    private void addStaveButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStaveButtonLabelMouseExited
        // TODO add your handling code here:
        this.addStaveButtonLabel.setBackground(new java.awt.Color(245,245,245));
    }//GEN-LAST:event_addStaveButtonLabelMouseExited

    //halo
    public void addStave(){
        this.noteEditorPanel.addStave();
        repaint();
        revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addStaveButtonLabel;
    private javax.swing.JButton composeFileButton;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel leftPanelHideLabel;
    private javax.swing.JLabel leftPanelShowLabel;
    private javax.swing.JPanel noteSheetEditPanel;
    private javax.swing.JButton saveFileButton;
    // End of variables declaration//GEN-END:variables
}
